#
#
#
---
default_ipv4_address: "{{ ansible_default_ipv4.address }}"
default_ipv6_address: "{{ ansible_default_ipv6.address }}"

# global firewall zone. should not be "trusted" on a production system
firewalld_zone: public

docker_repoprefix: docker.myurl.tld

diaspora_config_dir: /etc/opt/diaspora
diaspora_system_user: diaspora
diaspora_system_userid: 1011
diaspora_system_group: diaspora

# crypted password, applied to user module
# see http://docs.ansible.com/ansible/latest/faq.html#how-do-i-generate-crypted-passwords-for-the-user-module
#
# The value here is "change_me" (w/o quotes)
diaspora_system_password: "$6$gIfZDcwDqM.LUtab$W0gfIAXQ1lksYsUUfwpki83kERYEJcZSCe6Nd9u3gT52F.ini8I55yc.B2ypo65lmigdiwvw.xmaUw23woKPE1"
diaspora_homedir: /var/local/diaspora

diaspora_old_version: "v0.7.3.0"
diaspora_version: "v0.7.3.1"
diaspora_hostname: "my.pod.address"
diaspora_rewriteurl: "{{ diaspora_hostname.split('.') | join('\\.') }}"
diaspora_url: "https://{{ diaspora_hostname }}/"
diaspora_db_host: "172.17.0.1"
diaspora_redis_host: "redis://172.17.0.1"

diaspora_sidekiq_poolsize: 5

diaspora_routes_startpage: "home#default"
diaspora_assets_serve: "true"

diaspora_server_listen: "0.0.0.0:3000"
diaspora_server_rails_environment: "production"

diaspora_chat_enabled: "true"
diaspora_chat_server_bosh_proxy: "true"
diaspora_chat_server_bosh_address: "172.17.0.1"
diaspora_chat_server_bosh_bind: "/http-bind"

diaspora_privacy_statistics_user_counts: "true"
diaspora_privacy_statistics_post_counts: "true"
diaspora_privacy_statistics_comment_counts: "true"

diaspora_settings_enable_registrations: "false"
diaspora_settings_autofollow_on_join: "false"
diaspora_settings_autofollow_on_join_user: "hq@pod.diaspora.software"
diaspora_settings_invitations_open: "true"
diaspora_settings_invitations_count: 10
diaspora_settings_paypal_donations_enable: "false"
diaspora_settings_paypal_donations_currency: "USD"
diaspora_settings_paypal_donations_paypal_hosted_button_id: "change_me"
diaspora_settings_bitcoin_address: "PByXDkpibgHvNk8y9KbpR3ed3zXvMP5HFm"
diaspora_settings_captcha_enable: "true"
diaspora_settings_captcha_image_size: "120x20"
diaspora_settings_captcha_captcha_length: 8
diaspora_settings_captcha_image_style: "random"
diaspora_settings_captcha_distortion: "medium"
diaspora_settings_terms_enable: "true"
diaspora_settings_terms_jurisdiction: "Germany"
diaspora_settings_maintenance_remove_old_users_enable: "false"
diaspora_settings_maintenance_remove_old_users_after_days: 730
diaspora_settings_maintenance_remove_old_users_warn_days: 30
diaspora_settings_default_metas_title: "diaspora* social network"
diaspora_settings_default_metas_description: "diaspora* is the online social world where you are in control."

diaspora_settings_welcome_enabled: "true"
diaspora_settings_welcome_subject: "Welcome Message"
diaspora_settings_welcome_text: "Hello %{username}, welcome to diaspora."

diaspora_mail_enable: "true"

# the sender address for mail from diaspora. Must be valid with the mail server
diaspora_mail_sender_address: "{{ diaspora_system_user }}@{{ mail_domain }}"
diaspora_mail_method: "smtp"

# your smtp server
diaspora_mail_smtp_host: "{{ diaspora_hostname }}"
diaspora_mail_smtp_port: 587
diaspora_mail_smtp_authentication: "plain"

# The user as which the pod sends mail. Must be an authorized user on your smtp server
diaspora_mail_smtp_username: "{{ diaspora_system_user }}"

# Password for mail user. Unfortunately in clear text :(
diaspora_mail_smtp_password: "change_me"

diaspora_mail_smtp_domain: "{{ diaspora_hostname }}"
diaspora_mail_smtp_openssl_verify_mode: "none"

diaspora_admins_account: "your_admin_account"
diaspora_admins_podmin_email: "your_admin_mailadress"

diaspora_relay_outbound_send: "true"
diaspora_relay_outbound_url: "https://relay.iliketoast.net/receive/public"
diaspora_relay_inbound_subscribe: "true"
diaspora_relay_inbound_scope: "tags"
diaspora_relay_inbound_include_user_tags: "true"
diaspora_relay_inbound_pod_tags: "linux,diaspora"

# mail server used for the mail role
mail_server: "{{ diaspora_hostname }}"

# The domain for which the mailserver accepts mail. Might be different from mail_server
mail_domain: "{{ diaspora_hostname }}"

# ssl certificates and keys. The cert should have mail_server in its CN
# This setup is suited for letsencrypt certificates issued for the mail_server
mail_ssl_cert: /etc/letsencrypt/live/{{ mail_server }}/fullchain.pem
mail_ssl_key: /etc/letsencrypt/live/{{ mail_server }}/privkey.pem

mail_imap_maillocation: "maildir:~/.Mail"

# virtual host ssl configuration for the httpd proxy
# These settings here are suited for letsencrypt certificates generated by certbod --apache.
# Even if you have a different certificate provider, it is wise to have an include.conf file with
# your ssl settings (SSLEngine on, SSLCiphers, etc.) since that is required by all your virtual
# hosts with ssl enabled.
httpd_virthost_ssl_options_file: /etc/letsencrypt/options-ssl-apache.conf
httpd_virthost_ssl_cert: /etc/letsencrypt/live/{{ diaspora_hostname }}/cert.pem
httpd_virthost_ssl_key: /etc/letsencrypt/live/{{ diaspora_hostname }}/privkey.pem
httpd_virthost_ssl_certchain: /etc/letsencrypt/live/{{ diaspora_hostname }}/chain.pem

# The same certificates can (but not necessarily have to) be used for prosody.
# Except that prosody requires the fullchain instead the single cert.
prosody_ssl_cert: /etc/letsencrypt/live/{{ diaspora_hostname }}/fullchain.pem
prosody_ssl_key: /etc/letsencrypt/live/{{ diaspora_hostname }}/privkey.pem
...
