#
# diaspora database creation tasks
#
---
- name: create diaspora database user
  become: yes
  become_user: postgres
  postgresql_user:
    name: diaspora
    password: diaspora

- name: create diaspora database
  become: yes
  become_user: postgres
  postgresql_db:
    name: diaspora_production
    owner: diaspora
...