#
# Role to build diaspora-build and diaspora image
#
---
- name: copy diaspora-build docker source directory to host
  copy:
    src: diaspora-build
    dest: /usr/local/src/

- name: create the Dockerfile for build image
  template:
    src: diaspora-build/Dockerfile.j2
    dest: /usr/local/src/diaspora-build/Dockerfile

- name: check whether the diaspora-build image must be built (if container in current version is not present)
  shell: "docker images --format \"{% raw %}{{.Repository}}:{{.Tag}}{% endraw %}\" | grep 'diaspora-build' | wc -l"
  register: diasp_build_img_exists

- name: build the diaspora-build docker image 
  docker_image:
    path: /usr/local/src/diaspora-build
    name: "{{ docker_repoprefix }}/diaspora-build"
  when: diasp_build_img_exists.stdout == "0"

- name: make directory for diaspora build output
  file:
    path: /usr/local/src/diaspora/build
    owner: "{{ diaspora_system_user }}"
    group: "{{ diaspora_system_group }}"
    state: directory

- name: make directory for diaspora build config
  file:
    path: /usr/local/src/diaspora/build/config
    owner: "{{ diaspora_system_user }}"
    group: "{{ diaspora_system_group }}"
    state: directory

- name: template the diaspora Dockerfile to host
  template:
    src: diaspora/Dockerfile.j2
    dest: /usr/local/src/diaspora/Dockerfile

- name: create script directory
  file:
    path: /usr/local/src/diaspora/build/script
    state: directory
    owner: "{{ diaspora_system_user }}"
    group: "{{ diaspora_system_group }}"
    
- name: copy our version of script/server to host (w/o git dependency)
  copy:
    src: diaspora/script/server
    dest: /usr/local/src/diaspora/build/script/server
    owner: "{{ diaspora_system_user }}"
    group: "{{ diaspora_system_group }}"
    
- name: copy our ImageMagick policy.xml to diaspora docker src
  copy:
    src: ImageMagick/policy.xml
    dest: /usr/local/src/diaspora/

- name: check if diaspora must be built. That is, if diaspora-{{ diaspora_version }}.tar.gz exists
  stat:
    path: "/usr/local/src/diaspora/build/diaspora-{{ diaspora_version }}.tar.gz"
  register: diasp_tgz

- name: take backup of diaspora production database, if a new must be built (just to be paranoid)
  become: yes
  become_user: postgres
  command: "pg_dump diaspora_production -Ft -f diaspora_production.{{ '%Y%m%d%H%M%S' | strftime }}.dump"
  when: not diasp_tgz.stat.exists

- name: use a diaspora-build container to build diaspora version {{ diaspora_version }}
  docker_container:
    name: diaspora_build
    image: "{{ docker_repoprefix }}/diaspora-build"
    detach: no
    interactive: yes
    volumes:
      - "/usr/local/src/diaspora/build:/var/local/diaspora"
    env:
      git_tag: "{{ diaspora_version }}"
    state: started
  when: not diasp_tgz.stat.exists

- name: delete the build container
  docker_container:
    name: diaspora_build
    state: absent

- name: build the diaspora image itself
  docker_image:
    name: "{{ docker_repoprefix }}/diaspora"
    tag: "{{ diaspora_version }}"
    path: /usr/local/src/diaspora
...
