#
# diaspora setup from source files, database and docker image
#
---
- include_tasks: shutdown.yaml

- name: install redis cache
  yum:
    name: redis
    state: latest

- name: copy our version of redis.conf to /etc/redis/redis.conf
  copy:
    src: redis.conf
    dest: /etc/redis.conf
    backup: yes

- name: make sure redis is enabled and started
  service:
    name: redis
    state: restarted
    enabled: true

- name: ensure group diaspora with gid 1011 exists
  group:
    name: diaspora
    gid: 1011

- name: ensure diaspora system user with home /var/local/diaspora
  user:
    name: "{{ diaspora_system_user }}"
    state: present
    uid: "{{ diaspora_system_userid }}"
    group: "{{ diaspora_system_group }}"
    move_home: yes
    createhome: yes
    home: /var/local/diaspora
    password: "{{ diaspora_system_password }}"

- include_tasks: database.yaml

- name: check whether images must be built (if container in current version is not present)
  shell: "docker images --format \"{% raw %}{{.Repository}}:{{.Tag}}{% endraw %}\" | grep 'diaspora:{{ diaspora_version }}' | wc -l"
  register: diasp_img_exists

- include_tasks: dockerimages.yaml
  when: diasp_img_exists.stdout == "0"

- name: check if /var/local/diaspora directory must be created
  stat:
    path: /var/local/diaspora
  register: diasp_home

- name: copy diaspora files tar.gz to host if necessary
  copy:
    src: diaspora_files.tar.gz
    dest: /tmp/diaspora_files.tar.gz
  when: not diasp_home.stat.exists

- name: extract diaspora files if necessary
  command: tar -C /var/local --preserve-permissions --same-owner -xf /tmp/diaspora_files.tar.gz
  when: not diasp_home.stat.exists

- name: template out virtualhost config to httpd/conf.d/
  template:
    src: httpd/diaspora.conf.j2
    dest: /etc/httpd/conf.d/diaspora.conf
    backup: yes

- name: add ipv4 address of {{ diaspora_url }} to /etc/hosts (used by httpd to determine virtual host)
  lineinfile:
    path: /etc/hosts
    line: "{{ ansible_default_ipv4['address'] }}    {{ diaspora_url }}"

- name: add ipv6 address of {{ diaspora_url }} to /etc/hosts (used by httpd to determine virtual host)
  lineinfile:
    path: /etc/hosts
    line: "{{ ansible_default_ipv6['address'] }}    {{ diaspora_url }}"
  when: ansible_default_ipv6['address'] is defined

- include_tasks: startup.yaml
...