#
# Role to startup diaspora docker
#
---
- name: eventually create and definitely start diaspora container
  docker_container:
    name: "diaspora-{{ diaspora_version }}"
    image: "{{ docker_repoprefix }}/diaspora:{{ diaspora_version }}"
    published_ports:
      - "127.0.0.1:3000:3000"
    volumes:
      - "{{ diaspora_config_dir }}/diaspora.yml:/var/local/diaspora/diaspora/config/diaspora.yml:ro"
      - "{{ diaspora_config_dir }}/database.yml:/var/local/diaspora/diaspora/config/database.yml:ro"
      - "{{ diaspora_config_dir }}/routes.rb:/var/local/diaspora/diaspora/config/routes.rb:ro"
      - "diaspora-uploads:/var/local/diaspora/diaspora/public/uploads"
      - "diaspora-logs:/var/local/diaspora/diaspora/log"
    restart_policy: "unless-stopped"
    state: started
    restart: true
...