#
# Firewall rule tasks for proxy
#
---
- name: add firewall rule for http
  firewalld:
    zone: "{{ firewalld_zone }}"
    service: http
    permanent: true
    state: enabled
    immediate: yes

- name: add firewall rule for https
  firewalld:
    zone: "{{ firewalld_zone }}"
    service: https
    permanent: true
    state: enabled
    immediate: yes
