FROM centos:7
ENV diaspora_version {{ diaspora_version }}
RUN useradd -m -d /var/local/diaspora -u {{ diaspora_system_userid }} {{ diaspora_system_user }}
COPY --chown={{ diaspora_system_user }}:{{ diaspora_system_group }} build/diaspora-${diaspora_version}.tar.gz /tmp/

{% raw %}
RUN yum -y reinstall filesystem && yum -y update && \
	yum -y install epel-release && \
	yum -y install libcurl libxml2 libffi libxslt wget ImageMagick \
		nodejs postgresql-libs which bzip2 readline sqlite libyaml openssl && \
	yum clean all && rm -rf /var/cache/yum && \
    tar -xvz -C /var/local/diaspora --preserve-permissions --same-owner \
    	-f /tmp/diaspora-${diaspora_version}.tar.gz && \
    rm -f /tmp/diaspora-${diaspora_version}.tar.gz

COPY policy.xml /etc/ImageMagick-6/policy.xml

VOLUME /var/local/diaspora/diaspora/public/uploads
VOLUME /var/local/diaspora/diaspora/log
{% endraw %}

USER {{ diaspora_system_user }}:{{ diaspora_system_group }}

{% raw %}
WORKDIR /var/local/diaspora/diaspora
ENTRYPOINT ["/bin/bash", "-lc", "source /var/local/diaspora/.bash_profile && ./script/server"]
{% endraw %}